### ISSUE TITLE
Error during additional pipeline

### ISSUE THREAD

**Issue by chrisk1** [DevelopingHCP/structural-pipeline#1]
The pipeline fails during the additional pipeline stage, due to a path error. Running on Ubuntu 14.04 with a local installation, but processing files located in an sshfs-mounted remote drive. Tracing it back, there is a problem with:

**parameters/configuration.sh, line 4**
`export parameters_dir=$(dirname "$BASH_SOURCE")`

where `$(dirname "$BASH_SOURCE")` resolves to `./parameters` and hence the rest fails, as this isn't a complete path.

Replacing this line with a hard-coded path allows the script to run to completion:
`export parameters_dir=/home/username/structural-pipeline/parameters`

A universal solution (from https://stackoverflow.com/a/246128/1518749), that seems to work perfectly here is:
`export parameters_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`

Hope that helps!

**Comment by amakropoulos** [comment]
Thanks Chris, this is now fixed as you describe!
